[0m14:47:27.593963 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10505b150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105067fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105067f90>]}


============================== 14:47:27.602187 | 92381223-648b-447f-a5e9-57c84e9949a7 ==============================
[0m14:47:27.602187 [info ] [MainThread]: Running with dbt=1.9.6
[0m14:47:27.602543 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/yashpadiyar/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init dbtsnow', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m14:47:27.648518 [debug] [MainThread]: Starter project path: /Users/yashpadiyar/dbt_pipeline/venv/lib/python3.11/site-packages/dbt/include/starter_project
[0m14:47:27.667655 [info ] [MainThread]: 
Your new dbt project "dbtsnow" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:47:27.667922 [info ] [MainThread]: Setting up your profile.
[0m14:53:53.914737 [info ] [MainThread]: Profile dbtsnow written to /Users/yashpadiyar/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m14:53:53.922007 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 386.38254, "process_in_blocks": "0", "process_kernel_time": 0.252527, "process_mem_max_rss": "124059648", "process_out_blocks": "0", "process_user_time": 0.849346}
[0m14:53:53.924137 [debug] [MainThread]: Command `dbt init` succeeded at 14:53:53.923874 after 386.38 seconds
[0m14:53:53.924892 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105067b50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104543e10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10262ca10>]}
[0m14:53:53.925563 [debug] [MainThread]: Flushing usage events
[0m14:53:57.335275 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:48:48.619606 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107b65110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109df2650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109d4d210>]}


============================== 17:48:48.623584 | 4d94528e-f19d-4b47-8e2b-044e944a7442 ==============================
[0m17:48:48.623584 [info ] [MainThread]: Running with dbt=1.7.19
[0m17:48:48.624000 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/yashpadiyar/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run --select fact_rev', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:48:48.624437 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/yashpadiyar/dbt_pipeline/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:48:48.626906 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.049937043, "process_user_time": 0.959467, "process_kernel_time": 0.127462, "process_mem_max_rss": "110477312", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m17:48:48.627286 [debug] [MainThread]: Command `dbt run` failed at 17:48:48.627204 after 0.05 seconds
[0m17:48:48.627551 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10524f050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109d4c950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109d4d210>]}
[0m17:48:48.627983 [debug] [MainThread]: Flushing usage events
